pid /var/snap/game-server/current/nginx.pid;
daemon off;
worker_processes auto;

error_log syslog:server=unix:/dev/log warn;

events {
    worker_connections 1024;
}

http {
    access_log syslog:server=unix:/dev/log;
    include /snap/game-server/current/nginx/etc/nginx/mime.types;

    client_body_temp_path /var/snap/game-server/current/nginx/client_body_temp;
    proxy_temp_path /var/snap/game-server/current/nginx/proxy_temp;
    fastcgi_temp_path /var/snap/game-server/current/nginx/fastcgi_temp;
    uwsgi_temp_path /var/snap/game-server/current/nginx/uwsgi_temp;
    scgi_temp_path /var/snap/game-server/current/nginx/scgi_temp;

    upstream backend {
        server unix:/var/snap/game-server/current/backend.sock;
    }

    server {
        listen unix:/var/snap/game-server/common/web.socket;

        set_real_ip_from unix:;
        server_name localhost;

        root /snap/game-server/current/web/dist;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css application/json application/javascript text/javascript;

        include /var/snap/game-server/current/config/authelia-location.conf;
        include /var/snap/game-server/current/config/authelia-location-basic.conf;

        location /api/ {
            include /var/snap/game-server/current/config/proxy.conf;
            include /var/snap/game-server/current/config/authelia-authrequest-basic.conf;
            proxy_pass http://backend;
        }

        location / {
            include /var/snap/game-server/current/config/authelia-authrequest.conf;
            try_files $uri $uri/ /index.html;
        }
    }
}
